//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotWell.HRMS.HRMSWeb.AuthorizationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorizationService.IAuthorizationService")]
    public interface IAuthorizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/GetAuthorizationXml", ReplyAction="http://tempuri.org/IAuthorizationService/GetAuthorizationXmlResponse")]
        string GetAuthorizationXml(string _paramXmlText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/GetUserValidationXML", ReplyAction="http://tempuri.org/IAuthorizationService/GetUserValidationXMLResponse")]
        string GetUserValidationXML(string _paramXmlText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/GetUserInfomation", ReplyAction="http://tempuri.org/IAuthorizationService/GetUserInfomationResponse")]
        string GetUserInfomation(string _paramXmlText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/ChangeUserPassword", ReplyAction="http://tempuri.org/IAuthorizationService/ChangeUserPasswordResponse")]
        string ChangeUserPassword(string _paramXmlText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorizationServiceChannel : GotWell.HRMS.HRMSWeb.AuthorizationService.IAuthorizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizationServiceClient : System.ServiceModel.ClientBase<GotWell.HRMS.HRMSWeb.AuthorizationService.IAuthorizationService>, GotWell.HRMS.HRMSWeb.AuthorizationService.IAuthorizationService {
        
        public AuthorizationServiceClient() {
        }
        
        public AuthorizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAuthorizationXml(string _paramXmlText) {
            return base.Channel.GetAuthorizationXml(_paramXmlText);
        }
        
        public string GetUserValidationXML(string _paramXmlText) {
            return base.Channel.GetUserValidationXML(_paramXmlText);
        }
        
        public string GetUserInfomation(string _paramXmlText) {
            return base.Channel.GetUserInfomation(_paramXmlText);
        }
        
        public string ChangeUserPassword(string _paramXmlText) {
            return base.Channel.ChangeUserPassword(_paramXmlText);
        }
    }
}
