//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GotWell.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CentralServiceRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CentralServiceRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GotWell.LanguageResources.CentralServiceRes", typeof(CentralServiceRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name.
        /// </summary>
        public static string Daemon_Label_clnm {
            get {
                return ResourceManager.GetString("Daemon_Label_clnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron string.
        /// </summary>
        public static string Daemon_Label_cstr {
            get {
                return ResourceManager.GetString("Daemon_Label_cstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Daemon_Label_inte {
            get {
                return ResourceManager.GetString("Daemon_Label_inte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        public static string Daemon_Label_lgfi {
            get {
                return ResourceManager.GetString("Daemon_Label_lgfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last run result.
        /// </summary>
        public static string Daemon_Label_lrre {
            get {
                return ResourceManager.GetString("Daemon_Label_lrre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last run time.
        /// </summary>
        public static string Daemon_Label_lrtm {
            get {
                return ResourceManager.GetString("Daemon_Label_lrtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next run time.
        /// </summary>
        public static string Daemon_Label_nrtm {
            get {
                return ResourceManager.GetString("Daemon_Label_nrtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule ID.
        /// </summary>
        public static string Daemon_Label_scid {
            get {
                return ResourceManager.GetString("Daemon_Label_scid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule lock .
        /// </summary>
        public static string Daemon_Label_sclk {
            get {
                return ResourceManager.GetString("Daemon_Label_sclk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule name.
        /// </summary>
        public static string Daemon_Label_scnm {
            get {
                return ResourceManager.GetString("Daemon_Label_scnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule state.
        /// </summary>
        public static string Daemon_Label_scst {
            get {
                return ResourceManager.GetString("Daemon_Label_scst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID.
        /// </summary>
        public static string Daemon_Label_tkid {
            get {
                return ResourceManager.GetString("Daemon_Label_tkid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        public static string Daemon_Label_tknm {
            get {
                return ResourceManager.GetString("Daemon_Label_tknm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task state.
        /// </summary>
        public static string Daemon_Label_tkst {
            get {
                return ResourceManager.GetString("Daemon_Label_tkst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a invalid format,the right format is.
        /// </summary>
        public static string Field_Date_Format_Error_Message {
            get {
                return ResourceManager.GetString("Field_Date_Format_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too long,please to change!.
        /// </summary>
        public static string Field_Max_Length_Message {
            get {
                return ResourceManager.GetString("Field_Max_Length_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too short,please to change!.
        /// </summary>
        public static string Field_Min_Length_Message {
            get {
                return ResourceManager.GetString("Field_Min_Length_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageId.
        /// </summary>
        public static string Page_Label_Id {
            get {
                return ResourceManager.GetString("Page_Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        public static string Public_Add_WindowTitle {
            get {
                return ResourceManager.GetString("Public_Add_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Public_Button_Chinese {
            get {
                return ResourceManager.GetString("Public_Button_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Public_Button_Close {
            get {
                return ResourceManager.GetString("Public_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Public_Button_Confirm {
            get {
                return ResourceManager.GetString("Public_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Public_Button_Continue {
            get {
                return ResourceManager.GetString("Public_Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Period.
        /// </summary>
        public static string Public_Button_CurrentPeriod {
            get {
                return ResourceManager.GetString("Public_Button_CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Public_Button_English {
            get {
                return ResourceManager.GetString("Public_Button_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Public_Button_Exit {
            get {
                return ResourceManager.GetString("Public_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File List.
        /// </summary>
        public static string Public_Button_FileList {
            get {
                return ResourceManager.GetString("Public_Button_FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Public_Button_Help {
            get {
                return ResourceManager.GetString("Public_Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Public_Button_Role {
            get {
                return ResourceManager.GetString("Public_Button_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Public_Button_Save {
            get {
                return ResourceManager.GetString("Public_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User.
        /// </summary>
        public static string Public_Button_User {
            get {
                return ResourceManager.GetString("Public_Button_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        public static string Public_Confirm_Delete {
            get {
                return ResourceManager.GetString("Public_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Public_Confirm_Title {
            get {
                return ResourceManager.GetString("Public_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Window.
        /// </summary>
        public static string Public_Edit_WindowTitle {
            get {
                return ResourceManager.GetString("Public_Edit_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Rows.
        /// </summary>
        public static string Public_Grid_CalculationData {
            get {
                return ResourceManager.GetString("Public_Grid_CalculationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Rows.
        /// </summary>
        public static string Public_Grid_ImportData {
            get {
                return ResourceManager.GetString("Public_Grid_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Window.
        /// </summary>
        public static string Public_Help_WindowTitle {
            get {
                return ResourceManager.GetString("Public_Help_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Public_Import_WindowTitle {
            get {
                return ResourceManager.GetString("Public_Import_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Public_Label_Account {
            get {
                return ResourceManager.GetString("Public_Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified time.
        /// </summary>
        public static string Public_Label_lmtm {
            get {
                return ResourceManager.GetString("Public_Label_lmtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modifier.
        /// </summary>
        public static string Public_Label_lmur {
            get {
                return ResourceManager.GetString("Public_Label_lmur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Public_Menu_Authorization {
            get {
                return ResourceManager.GetString("Public_Menu_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon.
        /// </summary>
        public static string Public_Menu_daemon {
            get {
                return ResourceManager.GetString("Public_Menu_daemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Mgt.
        /// </summary>
        public static string Public_Menu_scapplic {
            get {
                return ResourceManager.GetString("Public_Menu_scapplic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Filter.
        /// </summary>
        public static string Public_Menu_scdatflt {
            get {
                return ResourceManager.GetString("Public_Menu_scdatflt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Mgt.
        /// </summary>
        public static string Public_Menu_scfunlst {
            get {
                return ResourceManager.GetString("Public_Menu_scfunlst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Mgt.
        /// </summary>
        public static string Public_Menu_scrole {
            get {
                return ResourceManager.GetString("Public_Menu_scrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mgt.
        /// </summary>
        public static string Public_Menu_scuser {
            get {
                return ResourceManager.GetString("Public_Menu_scuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Filter.
        /// </summary>
        public static string Public_Menu_scusrflt {
            get {
                return ResourceManager.GetString("Public_Menu_scusrflt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Setting.
        /// </summary>
        public static string Public_Menu_stsrvsch {
            get {
                return ResourceManager.GetString("Public_Menu_stsrvsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Setting.
        /// </summary>
        public static string Public_Menu_stsrvtsk {
            get {
                return ResourceManager.GetString("Public_Menu_stsrvtsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Failure.
        /// </summary>
        public static string Public_Message_AddBad {
            get {
                return ResourceManager.GetString("Public_Message_AddBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Successfully.
        /// </summary>
        public static string Public_Message_AddWell {
            get {
                return ResourceManager.GetString("Public_Message_AddWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name is existed,please checking!.
        /// </summary>
        public static string Public_Message_ApplicationExist {
            get {
                return ResourceManager.GetString("Public_Message_ApplicationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application name not exist,If want to add,please to use add function!.
        /// </summary>
        public static string Public_Message_AppNoExistToAdd {
            get {
                return ResourceManager.GetString("Public_Message_AppNoExistToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Fail.
        /// </summary>
        public static string Public_Message_CalculationFail {
            get {
                return ResourceManager.GetString("Public_Message_CalculationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Success.
        /// </summary>
        public static string Public_Message_CalculationSuccess {
            get {
                return ResourceManager.GetString("Public_Message_CalculationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarryForward Fail.
        /// </summary>
        public static string Public_Message_CarryForwardFail {
            get {
                return ResourceManager.GetString("Public_Message_CarryForwardFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarryForward Success.
        /// </summary>
        public static string Public_Message_CarryForwardSuccess {
            get {
                return ResourceManager.GetString("Public_Message_CarryForwardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check failed..
        /// </summary>
        public static string Public_Message_CheckBad {
            get {
                return ResourceManager.GetString("Public_Message_CheckBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Fail.
        /// </summary>
        public static string Public_Message_CheckFail {
            get {
                return ResourceManager.GetString("Public_Message_CheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check period status fail.
        /// </summary>
        public static string Public_Message_CheckPeriodStatusFail {
            get {
                return ResourceManager.GetString("Public_Message_CheckPeriodStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check period status success.
        /// </summary>
        public static string Public_Message_CheckPeriodStatusSuccess {
            get {
                return ResourceManager.GetString("Public_Message_CheckPeriodStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check step precondition fail.
        /// </summary>
        public static string Public_Message_CheckPreconditionFail {
            get {
                return ResourceManager.GetString("Public_Message_CheckPreconditionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check trace file.
        /// </summary>
        public static string Public_Message_CheckTraceFile {
            get {
                return ResourceManager.GetString("Public_Message_CheckTraceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Warning.
        /// </summary>
        public static string Public_Message_CheckWarning {
            get {
                return ResourceManager.GetString("Public_Message_CheckWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check success..
        /// </summary>
        public static string Public_Message_CheckWell {
            get {
                return ResourceManager.GetString("Public_Message_CheckWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cose period fail..
        /// </summary>
        public static string Public_Message_ClosePeriodFail {
            get {
                return ResourceManager.GetString("Public_Message_ClosePeriodFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close period successful..
        /// </summary>
        public static string Public_Message_ClosePeriodSuccess {
            get {
                return ResourceManager.GetString("Public_Message_ClosePeriodSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue to cancel?.
        /// </summary>
        public static string Public_Message_ConfirmCancel {
            get {
                return ResourceManager.GetString("Public_Message_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the period?.
        /// </summary>
        public static string Public_Message_ConfirmClosePeriod {
            get {
                return ResourceManager.GetString("Public_Message_ConfirmClosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue to calculation?.
        /// </summary>
        public static string Public_Message_ConfirmContinueCalculation {
            get {
                return ResourceManager.GetString("Public_Message_ConfirmContinueCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to import?.
        /// </summary>
        public static string Public_Message_ConfirmContinueImport {
            get {
                return ResourceManager.GetString("Public_Message_ConfirmContinueImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to open the period?.
        /// </summary>
        public static string Public_Message_ConfirmOpenPeriod {
            get {
                return ResourceManager.GetString("Public_Message_ConfirmOpenPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to do it?.
        /// </summary>
        public static string Public_Message_ConfirmReset2 {
            get {
                return ResourceManager.GetString("Public_Message_ConfirmReset2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data check fail.
        /// </summary>
        public static string Public_Message_DataCheckFail {
            get {
                return ResourceManager.GetString("Public_Message_DataCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data check success.
        /// </summary>
        public static string Public_Message_DataCheckSuccess {
            get {
                return ResourceManager.GetString("Public_Message_DataCheckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failure.
        /// </summary>
        public static string Public_Message_DeleteBad {
            get {
                return ResourceManager.GetString("Public_Message_DeleteBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfully.
        /// </summary>
        public static string Public_Message_DeleteWell {
            get {
                return ResourceManager.GetString("Public_Message_DeleteWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Failure.
        /// </summary>
        public static string Public_Message_EditBad {
            get {
                return ResourceManager.GetString("Public_Message_EditBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Successfully.
        /// </summary>
        public static string Public_Message_EditWell {
            get {
                return ResourceManager.GetString("Public_Message_EditWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Public_Message_Error {
            get {
                return ResourceManager.GetString("Public_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export to excel.
        /// </summary>
        public static string Public_Message_ExcelNoRecord {
            get {
                return ResourceManager.GetString("Public_Message_ExcelNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel fail.
        /// </summary>
        public static string Public_Message_ExportExcelFail {
            get {
                return ResourceManager.GetString("Public_Message_ExportExcelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename can not be empty or it is not an excel file!.
        /// </summary>
        public static string Public_Message_FileNotEmpty {
            get {
                return ResourceManager.GetString("Public_Message_FileNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failure.
        /// </summary>
        public static string Public_Message_ImportBad {
            get {
                return ResourceManager.GetString("Public_Message_ImportBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import denied..
        /// </summary>
        public static string Public_Message_ImportDenied {
            get {
                return ResourceManager.GetString("Public_Message_ImportDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Successfully.
        /// </summary>
        public static string Public_Message_ImportWell {
            get {
                return ResourceManager.GetString("Public_Message_ImportWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has exist!.
        /// </summary>
        public static string Public_Message_IsDuplicate {
            get {
                return ResourceManager.GetString("Public_Message_IsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to carryforward..
        /// </summary>
        public static string Public_Message_NoDataToCarryForward {
            get {
                return ResourceManager.GetString("Public_Message_NoDataToCarryForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stdprice of the material is not exists!.
        /// </summary>
        public static string Public_Message_NoStdPrice {
            get {
                return ResourceManager.GetString("Public_Message_NoStdPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open period fail..
        /// </summary>
        public static string Public_Message_OpenPeriodFail {
            get {
                return ResourceManager.GetString("Public_Message_OpenPeriodFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open period found, please close it first..
        /// </summary>
        public static string Public_Message_OpenPeriodFoundOpenDenied {
            get {
                return ResourceManager.GetString("Public_Message_OpenPeriodFoundOpenDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open period successfully..
        /// </summary>
        public static string Public_Message_OpenPeriodSuccess {
            get {
                return ResourceManager.GetString("Public_Message_OpenPeriodSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed maximun tabs count,please close some tabs!(Maximun:.
        /// </summary>
        public static string Public_Message_OpenTabsExceed {
            get {
                return ResourceManager.GetString("Public_Message_OpenTabsExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period is Closed.
        /// </summary>
        public static string Public_Message_PeriodIsClosed {
            get {
                return ResourceManager.GetString("Public_Message_PeriodIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period is Unused.
        /// </summary>
        public static string Public_Message_PeriodIsUnused {
            get {
                return ResourceManager.GetString("Public_Message_PeriodIsUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting fail..
        /// </summary>
        public static string Public_Message_PostingFail {
            get {
                return ResourceManager.GetString("Public_Message_PostingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting success..
        /// </summary>
        public static string Public_Message_PostingSuccess {
            get {
                return ResourceManager.GetString("Public_Message_PostingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Fail.
        /// </summary>
        public static string Public_Message_QueryFail {
            get {
                return ResourceManager.GetString("Public_Message_QueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejecting fail..
        /// </summary>
        public static string Public_Message_RejectingFail {
            get {
                return ResourceManager.GetString("Public_Message_RejectingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejecting success..
        /// </summary>
        public static string Public_Message_RejectingSuccess {
            get {
                return ResourceManager.GetString("Public_Message_RejectingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Fail..
        /// </summary>
        public static string Public_Message_ResetFail {
            get {
                return ResourceManager.GetString("Public_Message_ResetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation does not start,reset is unnecessary..
        /// </summary>
        public static string Public_Message_ResetIsUnnecessary {
            get {
                return ResourceManager.GetString("Public_Message_ResetIsUnnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Success..
        /// </summary>
        public static string Public_Message_ResetSuccess {
            get {
                return ResourceManager.GetString("Public_Message_ResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID is existed,please checking!.
        /// </summary>
        public static string Public_Message_RoleExist {
            get {
                return ResourceManager.GetString("Public_Message_RoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role ID not exist,If want to add,please to use add function!.
        /// </summary>
        public static string Public_Message_RoleNoExistToAdd {
            get {
                return ResourceManager.GetString("Public_Message_RoleNoExistToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failure.
        /// </summary>
        public static string Public_Message_SaveBad {
            get {
                return ResourceManager.GetString("Public_Message_SaveBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successfully.
        /// </summary>
        public static string Public_Message_SaveWell {
            get {
                return ResourceManager.GetString("Public_Message_SaveWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session TimeOut,Please try &lt;a href=&apos;Default.aspx&apos;&gt;&lt;font color=blue&gt;Login&lt;/font&gt;&lt;/a&gt; again.
        /// </summary>
        public static string Public_Message_SessionTimeOut {
            get {
                return ResourceManager.GetString("Public_Message_SessionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This step was calculated and states Completed..
        /// </summary>
        public static string Public_Message_StepCompleted {
            get {
                return ResourceManager.GetString("Public_Message_StepCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected step was completed, carryforward is denied..
        /// </summary>
        public static string Public_Message_StepCompletedCarryForwardDenied {
            get {
                return ResourceManager.GetString("Public_Message_StepCompletedCarryForwardDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step is locked..
        /// </summary>
        public static string Public_Message_StepLocked {
            get {
                return ResourceManager.GetString("Public_Message_StepLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waining.
        /// </summary>
        public static string Public_Message_Warning {
            get {
                return ResourceManager.GetString("Public_Message_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file,Please waiting....
        /// </summary>
        public static string Public_Message_Wating {
            get {
                return ResourceManager.GetString("Public_Message_Wating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string Public_PagingToolbar_EmptyMsg {
            get {
                return ResourceManager.GetString("Public_PagingToolbar_EmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Public_PagingToolbar_Total {
            get {
                return ResourceManager.GetString("Public_PagingToolbar_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Window.
        /// </summary>
        public static string Public_Query_WindowTitle {
            get {
                return ResourceManager.GetString("Public_Query_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Public_Tab_Summary {
            get {
                return ResourceManager.GetString("Public_Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Public_Title_Upload {
            get {
                return ResourceManager.GetString("Public_Title_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Public_Toolbar_Add {
            get {
                return ResourceManager.GetString("Public_Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string Public_Toolbar_Calculation {
            get {
                return ResourceManager.GetString("Public_Toolbar_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Public_Toolbar_Cancel {
            get {
                return ResourceManager.GetString("Public_Toolbar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarryForward.
        /// </summary>
        public static string Public_Toolbar_CarryForward {
            get {
                return ResourceManager.GetString("Public_Toolbar_CarryForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Public_Toolbar_CleanQuery {
            get {
                return ResourceManager.GetString("Public_Toolbar_CleanQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Public_Toolbar_Delete {
            get {
                return ResourceManager.GetString("Public_Toolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Public_Toolbar_Edit {
            get {
                return ResourceManager.GetString("Public_Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Public_Toolbar_Help {
            get {
                return ResourceManager.GetString("Public_Toolbar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Public_Toolbar_Import {
            get {
                return ResourceManager.GetString("Public_Toolbar_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an excel file to open.
        /// </summary>
        public static string Public_Toolbar_ImportExcelLabel {
            get {
                return ResourceManager.GetString("Public_Toolbar_ImportExcelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InExcel.
        /// </summary>
        public static string Public_Toolbar_InExcel {
            get {
                return ResourceManager.GetString("Public_Toolbar_InExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromExcel.
        /// </summary>
        public static string Public_Toolbar_OutExcel {
            get {
                return ResourceManager.GetString("Public_Toolbar_OutExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting.
        /// </summary>
        public static string Public_Toolbar_Posting {
            get {
                return ResourceManager.GetString("Public_Toolbar_Posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Public_Toolbar_Query {
            get {
                return ResourceManager.GetString("Public_Toolbar_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Public_Toolbar_Rejecting {
            get {
                return ResourceManager.GetString("Public_Toolbar_Rejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Public_Toolbar_Save {
            get {
                return ResourceManager.GetString("Public_Toolbar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string Public_Toolbar_Split {
            get {
                return ResourceManager.GetString("Public_Toolbar_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToExcel.
        /// </summary>
        public static string Public_Toolbar_ToExcel {
            get {
                return ResourceManager.GetString("Public_Toolbar_ToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Role_ID {
            get {
                return ResourceManager.GetString("Role_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete the system role.
        /// </summary>
        public static string RoleMgt_Message_CannotDelSysRole {
            get {
                return ResourceManager.GetString("RoleMgt_Message_CannotDelSysRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choice users!.
        /// </summary>
        public static string RoleMgt_Message_ChoiceUsers {
            get {
                return ResourceManager.GetString("RoleMgt_Message_ChoiceUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first input role base information,for example role id and application name!.
        /// </summary>
        public static string RoleMgt_Message_InputBaseInfor {
            get {
                return ResourceManager.GetString("RoleMgt_Message_InputBaseInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string scdatflt_Label_apnm {
            get {
                return ResourceManager.GetString("scdatflt_Label_apnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function ID.
        /// </summary>
        public static string scdatflt_Label_fnid {
            get {
                return ResourceManager.GetString("scdatflt_Label_fnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter desc.
        /// </summary>
        public static string scdatflt_Label_ftds {
            get {
                return ResourceManager.GetString("scdatflt_Label_ftds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter ID.
        /// </summary>
        public static string scdatflt_Label_ftid {
            get {
                return ResourceManager.GetString("scdatflt_Label_ftid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter text.
        /// </summary>
        public static string scdatflt_Label_fttx {
            get {
                return ResourceManager.GetString("scdatflt_Label_fttx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is disabled.
        /// </summary>
        public static string scdatflt_Label_isdi {
            get {
                return ResourceManager.GetString("scdatflt_Label_isdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string scdatflt_Label_tbnm {
            get {
                return ResourceManager.GetString("scdatflt_Label_tbnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Create.
        /// </summary>
        public static string scusrflt_Label_canc {
            get {
                return ResourceManager.GetString("scusrflt_Label_canc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Delete.
        /// </summary>
        public static string scusrflt_Label_cand {
            get {
                return ResourceManager.GetString("scusrflt_Label_cand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Select.
        /// </summary>
        public static string scusrflt_Label_cans {
            get {
                return ResourceManager.GetString("scusrflt_Label_cans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Update.
        /// </summary>
        public static string scusrflt_Label_canu {
            get {
                return ResourceManager.GetString("scusrflt_Label_canu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string scusrflt_Label_urid {
            get {
                return ResourceManager.GetString("scusrflt_Label_urid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string scusrflt_Label_urnm {
            get {
                return ResourceManager.GetString("scusrflt_Label_urnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Filters.
        /// </summary>
        public static string scusrflt_Lbl_DataFilter {
            get {
                return ResourceManager.GetString("scusrflt_Lbl_DataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Users.
        /// </summary>
        public static string scusrflt_Lbl_Users {
            get {
                return ResourceManager.GetString("scusrflt_Lbl_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow edit personal info.
        /// </summary>
        public static string Security_Label_alep {
            get {
                return ResourceManager.GetString("Security_Label_alep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string Security_Label_apnm {
            get {
                return ResourceManager.GetString("Security_Label_apnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        public static string Security_Label_apve {
            get {
                return ResourceManager.GetString("Security_Label_apve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available users.
        /// </summary>
        public static string Security_Label_availusers {
            get {
                return ResourceManager.GetString("Security_Label_availusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        public static string Security_Label_basis {
            get {
                return ResourceManager.GetString("Security_Label_basis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese desc.
        /// </summary>
        public static string Security_Label_cnde {
            get {
                return ResourceManager.GetString("Security_Label_cnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Pwd.
        /// </summary>
        public static string Security_Label_cpwd {
            get {
                return ResourceManager.GetString("Security_Label_cpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English desc.
        /// </summary>
        public static string Security_Label_ende {
            get {
                return ResourceManager.GetString("Security_Label_ende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func Id.
        /// </summary>
        public static string Security_Label_fnid {
            get {
                return ResourceManager.GetString("Security_Label_fnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func name.
        /// </summary>
        public static string Security_Label_fnnm {
            get {
                return ResourceManager.GetString("Security_Label_fnnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func status.
        /// </summary>
        public static string Security_Label_fsts {
            get {
                return ResourceManager.GetString("Security_Label_fsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Security_Label_functions {
            get {
                return ResourceManager.GetString("Security_Label_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func URL.
        /// </summary>
        public static string Security_Label_furl {
            get {
                return ResourceManager.GetString("Security_Label_furl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is system role.
        /// </summary>
        public static string Security_Label_issr {
            get {
                return ResourceManager.GetString("Security_Label_issr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is system user.
        /// </summary>
        public static string Security_Label_issu {
            get {
                return ResourceManager.GetString("Security_Label_issu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level No.
        /// </summary>
        public static string Security_Label_leno {
            get {
                return ResourceManager.GetString("Security_Label_leno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified time.
        /// </summary>
        public static string Security_Label_lmtm {
            get {
                return ResourceManager.GetString("Security_Label_lmtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modifier.
        /// </summary>
        public static string Security_Label_lmur {
            get {
                return ResourceManager.GetString("Security_Label_lmur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Security_Label_modu {
            get {
                return ResourceManager.GetString("Security_Label_modu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features.
        /// </summary>
        public static string Security_Label_nefe {
            get {
                return ResourceManager.GetString("Security_Label_nefe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permis.
        /// </summary>
        public static string Security_Label_perm {
            get {
                return ResourceManager.GetString("Security_Label_perm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent func Id.
        /// </summary>
        public static string Security_Label_pfid {
            get {
                return ResourceManager.GetString("Security_Label_pfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Security_Label_plfo {
            get {
                return ResourceManager.GetString("Security_Label_plfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Security_Label_pswd {
            get {
                return ResourceManager.GetString("Security_Label_pswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released by.
        /// </summary>
        public static string Security_Label_reby {
            get {
                return ResourceManager.GetString("Security_Label_reby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Security_Label_remk {
            get {
                return ResourceManager.GetString("Security_Label_remk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released time.
        /// </summary>
        public static string Security_Label_retm {
            get {
                return ResourceManager.GetString("Security_Label_retm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role desc.
        /// </summary>
        public static string Security_Label_rode {
            get {
                return ResourceManager.GetString("Security_Label_rode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        public static string Security_Label_roid {
            get {
                return ResourceManager.GetString("Security_Label_roid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Security_Label_role {
            get {
                return ResourceManager.GetString("Security_Label_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string Security_Label_ronm {
            get {
                return ResourceManager.GetString("Security_Label_ronm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role status.
        /// </summary>
        public static string Security_Label_rost {
            get {
                return ResourceManager.GetString("Security_Label_rost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role type.
        /// </summary>
        public static string Security_Label_roty {
            get {
                return ResourceManager.GetString("Security_Label_roty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected users.
        /// </summary>
        public static string Security_Label_selectedusers {
            get {
                return ResourceManager.GetString("Security_Label_selectedusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id.
        /// </summary>
        public static string Security_Label_sfid {
            get {
                return ResourceManager.GetString("Security_Label_sfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Security_Label_stus {
            get {
                return ResourceManager.GetString("Security_Label_stus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string Security_Label_urid {
            get {
                return ResourceManager.GetString("Security_Label_urid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Security_Label_urnm {
            get {
                return ResourceManager.GetString("Security_Label_urnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status.
        /// </summary>
        public static string Security_Label_urst {
            get {
                return ResourceManager.GetString("Security_Label_urst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        public static string Security_Label_urty {
            get {
                return ResourceManager.GetString("Security_Label_urty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Security_Label_users {
            get {
                return ResourceManager.GetString("Security_Label_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web URL.
        /// </summary>
        public static string Security_Label_wurl {
            get {
                return ResourceManager.GetString("Security_Label_wurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string SysUser_Domain {
            get {
                return ResourceManager.GetString("SysUser_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string SysUser_FullName {
            get {
                return ResourceManager.GetString("SysUser_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string SysUser_GroupName {
            get {
                return ResourceManager.GetString("SysUser_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Logon Time.
        /// </summary>
        public static string SysUser_LastLogonTime {
            get {
                return ResourceManager.GetString("SysUser_LastLogonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SysUser_UserName {
            get {
                return ResourceManager.GetString("SysUser_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        public static string Trace_Label_FileName {
            get {
                return ResourceManager.GetString("Trace_Label_FileName", resourceCulture);
            }
        }
    }
}
